SELECT P.NUM_DOC_PESSOA,
	P.NOME_PESSOA,
	CASE WHEN P.TIPO_PESSOA = 'F' THEN 'FISICA'
		WHEN P.TIPO_PESSOA = 'J' THEN 'JURIDICA'
        ELSE 'OUTROS' -- caso eu n queira que seja nulo
    END AS DESCR_TIPO_PESSOA,
    TD.DESCRICAO AS NACIONALIDADE
FROM PESSOAS P
		INNER JOIN TAB_DOMINIO TD
		ON P.NACIONALIDADE_COD = TD.COD_TABEÇA AND
			P.NACIONALIDADE_ITEM = TD_ITEM_TABELA
        
WHERE TRIM(UPPER(P.NOME_PESSOA)) LIKE CONCAT('%', TRIM(UPER('MaRia')), '%")
    
